In [95]:
import pandas as pd
import numpy as np

In [96]:
import pandas as pd
import numpy as np
# Set random seed for reproducibility
np.random.seed(42)
# Generate 1000 rows with 4 columns
n_rows = 1000
data = {
    'color': np.random.choice(['red', 'blue', 'green'], n_rows),
    'size': np.random.choice(['small', 'medium', 'large'], n_rows),
    'material': np.random.choice(['plastic', 'metal', 'wood'], n_rows),
    'price': np.random.randint(10, 500, n_rows)
}
df = pd.DataFrame(data)

# Display first few rows
print(df.head())
print(f"\nDataset shape: {df.shape}")

   color   size material  price
0  green  large    metal    423
1    red  large  plastic    351
2  green  large  plastic    229
3  green  large     wood    400
4    red  small  plastic    172

Dataset shape: (1000, 4)

In [97]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [98]:
x = df.drop(columns='price')
y = df.price
xtrain,xtest,ytrain,yest = train_test_split(x,y,train_size=0.8,random_state=42)

In [99]:
label_encoder = LabelEncoder()
''' 
# updated_xtrain = label_encoder.fit_transform(xtrain)
ValueError: y should be a 1d array, 
got an array of shape (800, 3) instead.

'''

' \n# updated_xtrain = label_encoder.fit_transform(xtrain)\nValueError: y should be a 1d array, \ngot an array of shape (800, 3) instead.\n\n'

In [100]:
label_encoder.fit_transform(xtrain['color'])

array([1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1,
       2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1,
       2, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2,
       1, 1, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 1, 2,
       2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1,
       2, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 0, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1,
       2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1, 1, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 0, 2, 1,
       0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 1, 2, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 2, 2, 0, 0, 2, 2, 2, 2, 0,
       0, 2, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2, 2, 1, 2, 1, 2, 0, 0, 2, 1,
       1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 2, 1, 2, 1, 0, 0, 1, 0, 2, 1, 1, 1, 2, 1, 2, 0, 1, 2, 1, 2, 0,
       2, 2, 0, 1, 1, 0, 2, 0, 0, 2, 2, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0, 2,
       0, 2, 2, 2, 0, 2, 0, 1, 1, 2, 2, 0, 1, 0, 2, 2, 1, 2, 2, 2, 1, 1,
       2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 2,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 2, 2, 0, 1, 1, 2, 2, 0, 2, 2, 1, 1, 1, 1, 0, 2, 1,
       0, 1, 0, 2, 2, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 0, 2, 2, 0, 2, 2, 1,
       1, 1, 0, 1, 0, 0, 2, 2, 0, 1, 1, 2, 1, 0, 2, 1, 0, 2, 2, 0, 0, 2,
       2, 1, 1, 2, 1, 1, 0, 1, 0, 0, 2, 1, 1, 0, 2, 0, 2, 2, 2, 1, 1, 1,
       2, 1, 2, 1, 1, 2, 1, 1, 1, 0, 2, 2, 1, 1, 0, 1, 0, 2, 1, 0, 2, 2,
       0, 0, 2, 0, 1, 0, 1, 2, 0, 1, 1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0,
       2, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 0, 0, 0, 1, 2, 2, 2,
       1, 0, 2, 1, 2, 1, 0, 1, 2, 2, 2, 0, 2, 0, 1, 1, 2, 1, 2, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 0, 2, 2, 2, 1, 1, 1, 1, 2, 2,
       2, 0, 1, 2, 1, 0, 0, 1, 0, 0, 2, 1, 0, 2, 0, 1, 0, 0, 0, 1, 2, 2,
       1, 1, 0, 0, 1, 0, 2, 0, 2, 1, 2, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 0,
       1, 0, 0, 0, 2, 2, 2, 2, 1, 0, 2, 2, 1, 0, 0, 1, 1, 1, 0, 0, 2, 2,
       0, 2, 0, 0, 1, 2, 1, 2, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 2, 1, 2, 0,
       0, 2, 1, 2, 1, 1, 0, 0, 2, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 2, 1, 1,
       0, 0, 0, 1, 0, 0, 2, 1, 1, 2, 1, 0, 0, 2, 1, 2, 0, 2, 0, 2, 1, 1,
       2, 1, 0, 2, 2, 0, 0, 1])

In [101]:
#new_input
# if one value is not present then it will give the error
new_input=['red','red']
label_encoder.transform(new_input)

array([2, 2])

In [102]:
#OneHotEncoder
hotEncoder=OneHotEncoder(sparse_output=False)       # 2. sparse_output --> it is used to get direct output by default it is True.
value = hotEncoder.fit_transform(xtrain)

#1. toArray() --> it is used for typecasting like to convert it into array
# value = value.toarray()
value

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [103]:
columns = hotEncoder.get_feature_names_out()

In [104]:
pd.DataFrame(value, columns=columns)

,color_blue,color_green,color_red,size_large,size_medium,size_small,material_metal,material_plastic,material_wood
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
795,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
796,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
797,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
798,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
799,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [105]:
'''hotEncoder.transform(xtest[['color','size']])
ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:'''

# valid syntax
hotEncoder.transform(xtest)

array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [106]:
# Handling unknown values
'''
i_p=[['red','large'],['blue','small']]
hotEncoder.transform(i_p)
ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.
'''

"\ni_p=[['red','large'],['blue','small']]\nhotEncoder.transform(i_p)\nValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.\n"

In [107]:
# The valid one
i_p=[['red','large','plastic'],['blue','small','wood']]
hotEncoder.transform(i_p)

c:\Users\idris\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [108]:
# For unknown values
'''
i_p=[['red','large','plastic'],['blue','small','wood']]
hotEncoder.transform(i_p)

ValueError: Found unknown categories ['red1'] in column 0 during transform
'''

"\ni_p=[['red','large','plastic'],['blue','small','wood']]\nhotEncoder.transform(i_p)\n\nValueError: Found unknown categories ['red1'] in column 0 during transform\n"

In [109]:
hotEncoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
updated_xtrain = hotEncoder.fit_transform(xtrain)

i_p=[['red1','large','plastic'],['blue','small','wood']]
hotEncoder.transform(i_p)

c:\Users\idris\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [110]:
hotEncoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

In [111]:
encoder=OrdinalEncoder()

In [112]:
updated_xtrain=encoder.fit_transform(xtrain)

In [113]:
updated_xtrain

array([[1., 2., 2.],
       [0., 1., 0.],
       [0., 2., 2.],
       ...,
       [0., 0., 1.],
       [0., 2., 1.],
       [1., 2., 1.]])

In [114]:
encoder.get_feature_names_out()

array(['color', 'size', 'material'], dtype=object)

In [115]:
'''
updated_xtrain=Oencoder.fit_transform(xtrain['color'])
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead

'''

"\nupdated_xtrain=Oencoder.fit_transform(xtrain['color'])\nValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. \nPass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead\n\n"

In [116]:
updated_xtest=encoder.transform(xtest)

In [117]:
updated_xtest

array([[2., 2., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 2., 1.],
       [0., 1., 0.],
       [2., 0., 1.],
       [1., 0., 1.],
       [2., 2., 1.],
       [2., 0., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [1., 2., 0.],
       [2., 0., 0.],
       [1., 1., 2.],
       [2., 0., 1.],
       [2., 0., 2.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 2., 1.],
       [0., 1., 1.],
       [2., 1., 1.],
       [0., 1., 2.],
       [1., 0., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 1., 1.],
       [2., 1., 0.],
       [2., 0., 2.],
       [0., 2., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [2., 2., 2.],
       [2., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 0., 1.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 2., 2.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 2.],
       [0., 0., 2.],
       [0., 2., 0.],
       [2., 2., 2.],
       [0., 2., 2.],
       [0., 2., 0.],
       [1., 1., 2.],
       [1., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [0., 0., 0.],
       [1., 2., 1.],
       [2., 1., 2.],
       [2., 2., 2.],
       [1., 2., 1.],
       [2., 1., 0.],
       [2., 2., 1.],
       [1., 1., 1.],
       [2., 0., 0.],
       [1., 0., 1.],
       [1., 2., 2.],
       [1., 2., 2.],
       [0., 2., 0.],
       [1., 1., 1.],
       [1., 1., 2.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 2., 1.],
       [1., 1., 2.],
       [0., 1., 1.],
       [0., 2., 2.],
       [2., 0., 0.],
       [0., 2., 1.],
       [0., 2., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [0., 2., 2.],
       [2., 2., 0.],
       [0., 0., 2.],
       [2., 0., 2.],
       [2., 0., 1.],
       [0., 0., 0.],
       [2., 0., 2.],
       [0., 1., 0.],
       [1., 1., 0.],
       [2., 0., 2.],
       [0., 2., 1.],
       [0., 0., 0.],
       [1., 1., 2.],
       [0., 1., 2.],
       [2., 0., 0.],
       [0., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.],
       [1., 1., 1.],
       [2., 0., 1.],
       [2., 0., 0.],
       [2., 0., 2.],
       [2., 2., 1.],
       [0., 0., 2.],
       [0., 0., 2.],
       [2., 0., 2.],
       [1., 2., 1.],
       [1., 2., 0.],
       [2., 0., 0.],
       [2., 1., 2.],
       [0., 0., 1.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 0., 0.],
       [2., 2., 0.],
       [0., 0., 0.],
       [2., 0., 0.],
       [2., 0., 0.],
       [2., 0., 2.],
       [1., 0., 2.],
       [0., 2., 2.],
       [2., 2., 0.],
       [2., 1., 2.],
       [0., 2., 2.],
       [0., 2., 2.],
       [2., 1., 1.],
       [1., 2., 1.],
       [2., 1., 2.],
       [0., 0., 1.],
       [2., 1., 2.],
       [0., 0., 0.],
       [2., 1., 0.],
       [1., 1., 1.],
       [1., 2., 2.],
       [1., 2., 0.],
       [0., 0., 2.],
       [2., 0., 0.],
       [2., 0., 2.],
       [2., 0., 0.],
       [0., 0., 2.],
       [1., 0., 2.],
       [2., 2., 1.],
       [2., 2., 2.],
       [0., 0., 1.],
       [1., 2., 2.],
       [0., 1., 2.],
       [2., 1., 2.],
       [2., 1., 2.],
       [2., 0., 2.],
       [0., 0., 0.],
       [0., 2., 0.],
       [2., 1., 1.],
       [2., 1., 2.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [2., 0., 1.],
       [0., 1., 1.],
       [2., 2., 0.],
       [1., 1., 0.],
       [2., 1., 2.],
       [1., 1., 2.],
       [1., 2., 1.],
       [1., 2., 1.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 1., 0.],
       [2., 2., 2.],
       [2., 1., 0.],
       [0., 1., 0.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 2., 0.],
       [2., 2., 2.],
       [1., 2., 0.],
       [0., 0., 0.],
       [1., 2., 1.],
       [1., 1., 0.],
       [0., 0., 0.],
       [0., 2., 0.],
       [0., 1., 0.],
       [2., 1., 0.],
       [0., 1., 2.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 2., 1.],
       [1., 2., 0.],
       [2., 0., 0.],
       [2., 2., 0.],
       [1., 2., 1.],
       [1., 1., 1.]])

In [118]:
'''
updated_xtest=Oencoder.transform(xtest['color'])

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead
'''

"\nupdated_xtest=Oencoder.transform(xtest['color'])\n\nValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. \nPass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead\n"

In [119]:
# Oencoder=OrdinalEncoder(handle_unknown='error')

encoder=OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)

updated_xtrain=encoder.fit_transform(xtrain)
updated_xtest=encoder.transform(xtest)

new_data=[['white', 'small','wood'],['red','small','wood']]

# new_data=pd.DataFrame(data=[['white','small','wood'],['red','medium','wood']], columns=['color','size','material'])
updated_new_data=[['white', 'small', 'wood'],['red', 'small','wood']]
updated_new_data= encoder.transform(new_data)

c:\Users\idris\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

In [120]:
# encoder=OrdinalEncoder(categories=[['green','blue','red']], handle_unknown='use_encoded_value',unknown_value=-1)
# encoder.fit_transform(xtrain)

''' ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,). 

It is wrong syntax, because xtrain is having 3 cols and categories=[[col_order]]
shape mismatching

When xtrain cols == col_orders
'''

' ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,). \n\nIt is wrong syntax, because xtrain is having 3 cols and categories=[[col_order]]\nshape mismatching\n\nWhen xtrain cols == col_orders\n'

In [121]:
encoder=OrdinalEncoder(categories=[['green','blue','red']], handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit_transform(xtrain[['color']])

'''

Here in order we just pass the one column values and in xtrain we also passing only one columns so didn't get any error

'''

"\n\nHere in order we just pass the one column values and in xtrain we also passing only one columns so didn't get any error\n\n"

In [122]:
'''encoder=OrdinalEncoder(categories=[['green','blue','red'],['small','medium','large'],['wood','metal','plastic']], handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit_transform(xtrain[['color','size']])

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

Because in order we mention the three columns but in xtrain we are passing the only two columns so we are getting the ValueError: Shape mismatch

'''

"encoder=OrdinalEncoder(categories=[['green','blue','red'],['small','medium','large'],['wood','metal','plastic']], handle_unknown='use_encoded_value',unknown_value=-1)\nencoder.fit_transform(xtrain[['color','size']])\n\nValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).\n\nBecause in order we mention the three columns but in xtrain we are passing the only two columns so we are getting the ValueError: Shape mismatch\n\n"

In [123]:
encoder=OrdinalEncoder(categories=[['blue','red','green'],['metal','plastic','wood'],['medium','large','small']], handle_unknown='use_encoded_value', unknown_value=-1)
encoder.fit_transform(xtrain[['color','size','material']])

array([[ 2., -1., -1.],
       [ 0., -1., -1.],
       [ 0., -1., -1.],
       ...,
       [ 0., -1., -1.],
       [ 0., -1., -1.],
       [ 2., -1., -1.]])

In [124]:
'''

encoder=OrdinalEncoder(categories=[['blue','red','green'],['medium','large','small'],['metal','plastic','wood']], handle_unknown='use_encoded_value')
encoder.fit_transform(xtrain[['color','size','material']])

TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.

'''

"\n\nencoder=OrdinalEncoder(categories=[['blue','red','green'],['medium','large','small'],['metal','plastic','wood']], handle_unknown='use_encoded_value')\nencoder.fit_transform(xtrain[['color','size','material']])\n\nTypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.\n\n"

In [125]:
encoder=TargetEncoder(cols=['color'])

In [126]:
encoder=TargetEncoder(cols=['color'], handle_unknown='value') # It handels the unknown value by assigning the avg of all target columns.
encoder.fit_transform(xtrain,ytrain)

          color    size material
29   253.164751   small     wood
535  256.408397  medium    metal
695  256.408397   small     wood
557  263.678700   small  plastic
836  253.164751   large  plastic
..          ...     ...      ...
106  263.678700   large  plastic
270  263.678700   small  plastic
860  256.408397   large  plastic
435  256.408397   small  plastic
102  253.164751   small  plastic

[800 rows x 3 columns]

In [127]:
'''obj_cols=xtrain.select_dtypes(include='object').columns
num_col=xtrain.select_dtypes(include='number').columns

It is used to differentiate which columns are categorical columns and which columns are numerical columns

'''

"obj_cols=xtrain.select_dtypes(include='object').columns\nnum_col=xtrain.select_dtypes(include='number').columns\n\nIt is used to differentiate which columns are categorical columns and which columns are numerical columns\n\n"

In [128]:
encoder.transform(xtest)

          color    size material
521  263.678700   small    metal
737  263.678700   small    metal
740  256.408397   small    metal
660  253.164751   small  plastic
411  256.408397  medium    metal
..          ...     ...      ...
408  253.164751   small    metal
332  263.678700   large    metal
208  263.678700   small    metal
613  253.164751   small  plastic
78   253.164751  medium  plastic

[200 rows x 3 columns]

In [129]:
'''

new_input=[['red','small','wood1']]
encoder.transform(new_input)

KeyError: 'color'

'''

"\n\nnew_input=[['red','small','wood1']]\nencoder.transform(new_input)\n\nKeyError: 'color'\n\n"

In [136]:
# new_input=[['red','small','wood1']]
new_input=pd.DataFrame({
    'color':['red'], 'size':['small'], 'material':['wood1']
})
encoder.transform(new_input)

# When we are  passing a new_inputwe have to pass it in form of dictionary, we don't paas the new_input in the form dictionary it will give KeyError

      color   size material
0  263.6787  small    wood1